
heat_template_version: 2015-10-15


parameters:
  floating_network:
    type: string
    default: ext-net
  image:
    type: string
    default: cirros-0.3.4-x86_64-disk.img
  flavor:
    type: string
    default: 1C-0.5GB
  key_name:
    type: string
    default: mykey

