
heat_template_version: 2015-10-15


parameters:
  floating_network:
    type: string
    default: floating
  image:
    type: string
    default: cd498f49-6766-4bba-82bd-5433d3656b84
  flavor:
    type: string
    default: m1.tiny
  key_name:
    type: string
    default: mykey
  timeout: # NEW
    type: number
    description: Timeout for stack creation to finish
    default: 300


resources:

  mynetwork:
    type: OS::Neutron::Net
    properties:
      name: mynet


  mysubnet:
    type: OS::Neutron::Subnet
    properties:
      cidr: 10.0.0.1/24
      name: mysubnet
      network:
        get_resource: mynetwork

  myconfig:
    type: "OS::Heat::CloudConfig"
    properties:
      cloud_config:
        package_update: false
        package_upgrade: false
        packages:
          - emacs-nox
          - git
        runcmd:
          - echo 'Hello, World' >> /etc/motd
          - { get_attr: ['all_done_handle', 'curl_cli'] } # NEW


  all_done: # NEW
    type: OS::Heat::WaitCondition
    properties:
      handle: {get_resource: all_done_handle}
      count: 1
      timeout: {get_param: timeout}


  all_done_handle: # NEW
    type: OS::Heat::WaitConditionHandle


  myserver:
    type: OS::Nova::Server
    properties:
      name: myserver
      config_drive: true
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: myport }
      user_data_format: RAW
      user_data: { get_resource: myconfig }

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network:
          get_param: floating_network


  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: router }
      subnet: { get_resource: mysubnet }


  myfloatingip:
    type: OS::Neutron::FloatingIP
    properties:
      port_id: { get_resource: myport }
      floating_network:
        get_param: floating_network


  allow_inbound:
    type: OS::Neutron::SecurityGroup
    properties:
      description: "Allow inbound SSH and ICMP traffic"
      name: allow SSH and ICMP from anywhere
      rules:
        - direction: ingress
          remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp


  myport:
    type: OS::Neutron::Port
    properties:
      network:
        get_resource: mynetwork
      security_groups:
        - get_resource: allow_inbound


outputs:
  floating_ip:
    value:
      get_attr:
        - myfloatingip
        - floating_ip_address

