
heat_template_version: 2015-10-15


parameters:
  floating_network:
    type: string
    default: ext-net
  image:
    type: string
    default: cirros-0.3.4-x86_64-disk.img
  flavor:
    type: string
    default: 1C-0.5GB
  key_name:
    type: string


resources:

  mynetwork:
    type: OS::Neutron::Net
    properties:
      name: mynet


  mysubnet:
    type: OS::Neutron::Subnet
    properties:
      cidr: 10.0.0.1/24
      name: mysubnet
      network:
        get_resource: mynetwork


  myport:
    type: OS::Neutron::Port
    properties:
      network:
        get_resource: mynetwork

